
services:
  db:
    image: postgres:15
    container_name: social_media_feeds_backend_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:6379"
  
  backend:
    build: .
    container_name: social_media_feeds_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: